project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - AndiStory.qmd

website:
  title: "Lean Analytics Journey"
  site-url: https://YavinOwens.github.io/What-is-a-Data-Analyst
  repo-url: https://github.com/YavinOwens/What-is-a-Data-Analyst
  repo-actions: [edit, issue]
  page-navigation: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Andi's Story"
        href: AndiStory.qmd
    right:
      - icon: github
        href: https://github.com/YavinOwens/What-is-a-Data-Analyst

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    highlight-style: github

execute:
  echo: false
  warning: false
  freeze: auto

resources:
  - styles.css

project-list:
  - index.qmd
  - AndiStory.qmd 