project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - AndiStory.qmd
    - analytical_engineering_docs.qmd
    - project_planning.qmd
    - meeting_templates.qmd
    - findings_templates.qmd
    - issues_and_bugs.qmd
    - reference_materials.qmd
    - analysis_notebooks.qmd
    - data_quality_checks.qmd
    - team_wiki.qmd

website:
  title: "Lean Analytics Journey"
  site-url: https://YavinOwens.github.io/What-is-a-Data-Analyst
  repo-url: https://github.com/YavinOwens/What-is-a-Data-Analyst
  repo-actions: [edit, issue]
  page-navigation: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Andi's Story"
        href: AndiStory.qmd
      - text: "Eng Docs"
        href: analytical_engineering_docs.qmd
      - text: "Planning"
        href: project_planning.qmd
      - text: "Meetings"
        href: meeting_templates.qmd
      - text: "Findings"
        href: findings_templates.qmd
      - text: "Analysis Notebooks"
        href: analysis_notebooks.qmd
      - text: "Quality Checks"
        href: data_quality_checks.qmd
      - text: "Team Wiki"
        href: team_wiki.qmd
    right:
      - icon: github
        href: https://github.com/YavinOwens/What-is-a-Data-Analyst

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    highlight-style: github
    fig-format: png
    fig-width: 8
    fig-height: 6
    fig-dpi: 300

execute:
  echo: false
  warning: false
  error: false
  freeze: auto

resources:
  - styles.css

project-list:
  - index.qmd
  - AndiStory.qmd
  - analytical_engineering_docs.qmd
  - project_planning.qmd
  - meeting_templates.qmd
  - findings_templates.qmd
  - issues_and_bugs.qmd
  - reference_materials.qmd
  - analysis_notebooks.qmd
  - data_quality_checks.qmd
  - team_wiki.qmd 