project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - AndiStory.qmd
    - analytical_engineering_docs.qmd
    - project_planning.qmd
    - meeting_templates.qmd
    - findings_templates.qmd
    - issues_and_bugs.qmd
    - reference_materials.qmd
    - analysis_notebooks.qmd
    - data_quality_checks.qmd

website:
  title: "Lean Analytics Journey"
  site-url: https://YavinOwens.github.io/What-is-a-Data-Analyst
  repo-url: https://github.com/YavinOwens/What-is-a-Data-Analyst
  repo-actions: [edit, issue]
  page-navigation: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Andi's Story"
        href: AndiStory.qmd
      - text: "Documentation"
        menu:
          - text: "Engineering Docs"
            href: docs/analytical_engineering_docs.html
          - text: "Project Planning"
            href: docs/project_planning.html
          - text: "Meeting Templates"
            href: docs/meeting_templates.html
          - text: "Findings Templates"
            href: docs/findings_templates.html
          - text: "Issues and Bugs"
            href: docs/issues_and_bugs.html
          - text: "Reference Materials"
            href: docs/reference_materials.html
          - text: "Analysis Notebooks"
            href: docs/analysis_notebooks.html
          - text: "Data Quality Checks"
            href: docs/data_quality_checks.html
    right:
      - icon: github
        href: https://github.com/YavinOwens/What-is-a-Data-Analyst

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    highlight-style: github
    fig-format: png
    fig-width: 8
    fig-height: 6
    fig-dpi: 300

execute:
  echo: false
  warning: false
  error: false
  freeze: auto

resources:
  - styles.css

project-list:
  - index.qmd
  - AndiStory.qmd
  - analytical_engineering_docs.qmd
  - project_planning.qmd
  - meeting_templates.qmd
  - findings_templates.qmd
  - issues_and_bugs.qmd
  - reference_materials.qmd
  - analysis_notebooks.qmd
  - data_quality_checks.qmd 